services:
  app:
    build:
      context: ..
      dockerfile: spoticli-backend/Dockerfile.app
    container_name: spoticli-app
    environment:
      STREAM_SEGMENT_SIZE: "1000000"
      FRAME_CLUSTER_SIZE: "600"
      DB_HOST: db
      DB_PORT: "3306"
      DB_USERNAME: ADMIN
      DB_PASSWORD: ADMIN
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-test}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-test}"
      AWS_REGION: "${AWS_REGION:-us-east-1}"
      AWS_ENDPOINT_URL: "${AWS_ENDPOINT_URL:-http://localstack:4566}"
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: spoticli-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SPOTICLI_DB
      MYSQL_USER: ADMIN
      MYSQL_PASSWORD: ADMIN
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  localstack:
    image: localstack/localstack:latest
    ports:
      # S3 uses port 4566 by default in LocalStack
      - "4566:4566"
      - "4510-4559:4510-4559" # required for newer versions
      - "8055:8055" # LocalStack web user interface
    environment:
      # Specifies which services to run - add more for Terraform practice
      SERVICES: s3,rds,ecs,ec2,iam,cloudwatch,logs
      # Optional: Sets a fixed access key and secret key for local use
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_REGION: "us-east-1"
      LOCALSTACK_ARCH: native
      # Enables a user interface to view resources
      USE_SSL: "false"
      EDGE_PORT: 4566
      DEBUG: 1
    volumes:
      # Persists data across container restarts
      - localstack_data:/var/lib/localstack
      - "./init_s3.py:/etc/localstack/init/ready.d/init-s3.py"  # ready hook
      # Initialization hooks (optional): mount a directory with scripts to run on startup
      # - ./aws-init:/etc/localstack/init/ready.d/
    restart: always
volumes:
  db-data:
  localstack_data: